In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('../raw_data/investments_VC.csv', encoding='latin1', low_memory=False)

In [4]:
data.shape

(54294, 39)

In [5]:
data.dtypes

permalink                object
name                     object
homepage_url             object
category_list            object
 market                  object
 funding_total_usd       object
status                   object
country_code             object
state_code               object
region                   object
city                     object
funding_rounds          float64
founded_at               object
founded_month            object
founded_quarter          object
founded_year            float64
first_funding_at         object
last_funding_at          object
seed                    float64
venture                 float64
equity_crowdfunding     float64
undisclosed             float64
convertible_note        float64
debt_financing          float64
angel                   float64
grant                   float64
private_equity          float64
post_ipo_equity         float64
post_ipo_debt           float64
secondary_market        float64
product_crowdfunding    float64
round_A                 float64
round_B                 float64
round_C                 float64
round_D                 float64
round_E                 float64
round_F                 float64
round_G                 float64
round_H                 float64
dtype: object

In [6]:
data.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
data.head(3).T

,0,1,2
permalink,/organization/waywire,/organization/tv-communications,/organization/rock-your-paper
name,#waywire,&TV Communications,'Rock' Your Paper
homepage_url,http://www.waywire.com,http://enjoyandtv.com,http://www.rockyourpaper.org
category_list,|Entertainment|Politics|Social Media|News|,|Games|,|Publishing|Education|
market,News,Games,Publishing
funding_total_usd,"17,50,000","40,00,000","40,000"
status,acquired,operating,operating
country_code,USA,USA,EST
state_code,NY,CA,NaN
region,New York City,Los Angeles,Tallinn
city,New York,Los Angeles,Tallinn
funding_rounds,1.0,2.0,1.0
founded_at,2012-06-01,NaN,2012-10-26
founded_month,2012-06,NaN,2012-10
founded_quarter,2012-Q2,NaN,2012-Q4
founded_year,2012.0,NaN,2012.0
first_funding_at,2012-06-30,2010-06-04,2012-08-09
last_funding_at,2012-06-30,2010-09-23,2012-08-09
seed,1750000.0,0.0,40000.0
venture,0.0,4000000.0,0.0
equity_crowdfunding,0.0,0.0,0.0
undisclosed,0.0,0.0,0.0
convertible_note,0.0,0.0,0.0
debt_financing,0.0,0.0,0.0
angel,0.0,0.0,0.0
grant,0.0,0.0,0.0
private_equity,0.0,0.0,0.0
post_ipo_equity,0.0,0.0,0.0
post_ipo_debt,0.0,0.0,0.0
secondary_market,0.0,0.0,0.0
product_crowdfunding,0.0,0.0,0.0
round_A,0.0,0.0,0.0
round_B,0.0,0.0,0.0
round_C,0.0,0.0,0.0
round_D,0.0,0.0,0.0
round_E,0.0,0.0,0.0
round_F,0.0,0.0,0.0
round_G,0.0,0.0,0.0
round_H,0.0,0.0,0.0

In [8]:
data.describe()

,funding_rounds,founded_year,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
count,49438.000000,38482.000000,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,...,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04
mean,1.696205,2007.359129,2.173215e+05,7.501051e+06,6.163322e+03,1.302213e+05,2.336410e+04,1.888157e+06,6.541898e+04,1.628453e+05,...,3.845592e+04,7.074227e+03,1.243955e+06,1.492891e+06,1.205356e+06,7.375261e+05,3.424682e+05,1.697692e+05,5.767067e+04,1.423197e+04
std,1.294213,7.579203,1.056985e+06,2.847112e+07,1.999048e+05,2.981404e+06,1.432046e+06,1.382046e+08,6.582908e+05,5.612088e+06,...,3.864461e+06,4.282166e+05,5.531974e+06,7.472704e+06,7.993592e+06,9.815218e+06,5.406915e+06,6.277905e+06,5.252312e+06,2.716865e+06
min,1.000000,1902.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000,2006.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000,2010.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.000000,2012.000000,2.500000e+04,5.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,18.000000,2014.000000,1.300000e+08,2.351000e+09,2.500000e+07,2.924328e+08,3.000000e+08,3.007950e+10,6.359026e+07,7.505000e+08,...,6.806116e+08,7.200000e+07,3.190000e+08,5.420000e+08,4.900000e+08,1.200000e+09,4.000000e+08,1.060000e+09,1.000000e+09,6.000000e+08

In [9]:
data['status'].value_counts(dropna=False)

status
operating    41829
NaN           6170
acquired      3692
closed        2603
Name: count, dtype: int64

In [10]:
data.isna().sum().sort_values(ascending=False)

state_code              24133
founded_month           15812
founded_year            15812
founded_quarter         15812
founded_at              15740
city                    10972
country_code            10129
region                  10129
 market                  8824
category_list            8817
homepage_url             8305
status                   6170
name                     4857
post_ipo_debt            4856
secondary_market         4856
product_crowdfunding     4856
round_A                  4856
round_B                  4856
permalink                4856
round_C                  4856
round_D                  4856
round_E                  4856
private_equity           4856
round_F                  4856
round_G                  4856
post_ipo_equity          4856
venture                  4856
grant                    4856
angel                    4856
debt_financing           4856
convertible_note         4856
undisclosed              4856
equity_crowdfunding      4856
seed                     4856
last_funding_at          4856
first_funding_at         4856
funding_rounds           4856
 funding_total_usd       4856
round_H                  4856
dtype: int64

In [11]:
(data.isnull().mean() * 100).round(1).sort_values(ascending=False).astype(str) + '%'

state_code              44.4%
founded_year            29.1%
founded_quarter         29.1%
founded_month           29.1%
founded_at              29.0%
city                    20.2%
country_code            18.7%
region                  18.7%
 market                 16.3%
category_list           16.2%
homepage_url            15.3%
status                  11.4%
round_C                  8.9%
post_ipo_debt            8.9%
secondary_market         8.9%
product_crowdfunding     8.9%
round_A                  8.9%
round_B                  8.9%
permalink                8.9%
round_D                  8.9%
round_E                  8.9%
private_equity           8.9%
round_F                  8.9%
round_G                  8.9%
post_ipo_equity          8.9%
venture                  8.9%
grant                    8.9%
angel                    8.9%
debt_financing           8.9%
convertible_note         8.9%
undisclosed              8.9%
equity_crowdfunding      8.9%
name                     8.9%
seed                     8.9%
last_funding_at          8.9%
first_funding_at         8.9%
funding_rounds           8.9%
 funding_total_usd       8.9%
round_H                  8.9%
dtype: object

In [12]:
data[data['status'].isna()].head(10)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
5,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,"70,00,000",NaN,USA,FL,Ft. Lauderdale,...,0.0,0.0,0.0,7000000.0,0.0,0.0,0.0,0.0,0.0,0.0
67,/organization/1c-company,1C Company,http://1c.ru/eng,|Video Games|Games|Software|,Software,"20,00,00,000",NaN,RUS,NaN,Moscow,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
89,/organization/1st-merchant-funding,1st Merchant Funding,http://www.1stmerchantfunding.com/,|Financial Services|,Financial Services,"1,00,00,000",NaN,USA,FL,Miami,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121,/organization/24h00,24h00,http://www.boosket.com/,NaN,NaN,-,NaN,FRA,NaN,Paris,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
238,/organization/3nder,3nder,http://www.3nderapp.com,|iOS|Online Dating|Mobile|Location Based Servi...,Social Media,-,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
433,/organization/99-fahrenheit,99 Fahrenheit,NaN,|Finance|,Finance,"13,80,700",NaN,ITA,NaN,Milan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
465,/organization/a-bit-lucky,A Bit Lucky,http://www.abitlucky.com,|Social Games|Games|,Social Games,"1,03,12,103",NaN,USA,CA,SF Bay Area,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
485,/organization/a-power-energy-generation,A-Power Energy Generation Systems,http://www.apowerenergy.com/EN,|Clean Technology|,Clean Technology,"1,02,00,000",NaN,CHN,NaN,Shenyang,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
496,/organization/a2b,A2B,http://www.a2b.ru/,NaN,NaN,"5,00,000",NaN,RUS,NaN,St. Petersburg,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
639,/organization/accelera-innovations,Accelera Innovations,http://accelerainnovations.com,|Health and Wellness|,Health and Wellness,"20,00,00,000",NaN,USA,IL,Chicago,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0